"""initial schema

Revision ID: 11049cb9f0cf
Revises: 
Create Date: 2026-06-21 14:33:54.410220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11049cb9f0cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otps_phone'), ['phone'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('notif_attendance', sa.Boolean(), nullable=False),
    sa.Column('notif_tuition', sa.Boolean(), nullable=False),
    sa.Column('notif_report', sa.Boolean(), nullable=False),
    sa.Column('dnd_start', sa.String(length=5), nullable=True),
    sa.Column('dnd_end', sa.String(length=5), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('full_legal_name', sa.String(length=200), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_phone'), ['phone'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('default_fee', sa.Float(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('zalo_group_id', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_class_id'), ['class_id'], unique=False)

    op.create_table('attendance_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sessions_class_id'), ['class_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_class_id'), ['class_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('parent_phone', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('absence_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_session_id'), ['session_id'], unique=False)

    op.create_table('makeups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('confirmed_option', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id')
    )
    op.create_table('student_fees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('tuitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tuitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuitions_class_id'), ['class_id'], unique=False)

    op.create_table('makeup_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('makeup_id', sa.String(length=36), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('voter_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['makeup_id'], ['makeups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('makeup_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_makeup_votes_makeup_id'), ['makeup_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('makeup_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_makeup_votes_makeup_id'))

    op.drop_table('makeup_votes')
    with op.batch_alter_table('tuitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuitions_class_id'))

    op.drop_table('tuitions')
    op.drop_table('student_fees')
    op.drop_table('makeups')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_session_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_class_id'))

    op.drop_table('students')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_class_id'))

    op.drop_table('reports')
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_class_id'))

    op.drop_table('attendance_sessions')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_class_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_teacher_id'))

    op.drop_table('classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_phone'))

    op.drop_table('teachers')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otps_phone'))

    op.drop_table('otps')
    # ### end Alembic commands ###
